### PR TITLE
Clear the shipping rate and shipping rate id when a new shipping addess is set

### LINKED ISSUE #16: Setting a shipping address should clear the ShippingRate and ShippingRateId
# Description
There is an issue with trying to change the shipping address on a Checkout.

# Steps to reproduce:

* create a Checkout with a Shipping Address
* do buyClient.createCheckout(...) to create the Checkout on the server
* get shipping rates for the Checkout
* set the shipping rate on the Checkout
* do buyClient.updateCheckout(...) to update the Checkout on the server with the shipping rate
* set a new shipping address on the local checkout
* do buyClient.updateCheckout(...)
* The last step will fail, with an invalid Shipping Rate id error.

The shipping rate and shipping rate id are tied to the shipping address.  If we change the shipping address, it invalidates the old shipping rate and id.
Clearing the shippingRate and shippingRateId fields on the checkout before calling the update with the new shipping address fixes this problem.

### PR DESCRIPTION
**Pull request by krisorr**
Fixes #16 

@dave-pelletier please review.
@runmad please review.

### CODE REVIEW

File: MobileBuy/buy/src/androidTest/java/com/shopify/buy/service/BuyTest.java [hunk 1]
```diff
@@ -535,6 +549,21 @@ private Address getShippingAddress() {
         return shippingAddress;
     }
 
+    private Address getShippingAddressTwo() {
+        Address shippingAddress = new Address();
```
Comment (runmad) [inline MobileBuy/buy/src/androidTest/java/com/shopify/buy/service/BuyTest.java]: Could you create the second one with `getShippingAddress()` and then just change the city, since that's the only thing changing?

Comment (krisorr) [inline MobileBuy/buy/src/androidTest/java/com/shopify/buy/service/BuyTest.java]: Sure, that is fair, done.

File: MobileBuy/buy/src/androidTest/java/com/shopify/buy/service/BuyTest.java [hunk 2]
```diff
@@ -226,13 +226,30 @@ public void testFetchingShippingRatesWithInvalidCheckout() throws InterruptedExc
...
     }
 
+    public void testChangedShippingAddress() throws InterruptedException {
+        createValidCheckout();
+        fetchShippingRates(HttpStatus.SC_OK);
+        setShippingRate();
+
+        Address address = checkout.getShippingAddress();
+        address.setCity("Toronto");
+
```
Comment (runmad) [inline MobileBuy/buy/src/androidTest/java/com/shopify/buy/service/BuyTest.java]: Not sure if the below functions are needed. At this point, just check if the shipping rate has been invalidated?

Comment (krisorr) [inline MobileBuy/buy/src/androidTest/java/com/shopify/buy/service/BuyTest.java]: It is not entirely necessary, but I would like to have it in place to match the rest of the integration functions in this file.

**Comment by dave-pelletier** [comment]
It looks like the last commit reverted the fix. Don't we need to clear the shipping rate in setShippingAddress()?

**Comment by krisorr** [comment]
@dave-pelletier - I changed it to an explicit clearing of the shipping rate.
Any time you change the shipping address or add/remove a discount, the shipping rate should be cleared  before trying to update the checkout, or if an error of “if you get an invalid shipping rate” is returned the shipping rate will need to be cleared and re-polled.

To clear the shipping rate:
`setShippingRate(null);`

**Comment by dave-pelletier** [comment]
:rocket:
