### PR TITLE
Task/default address

### LINKED ISSUE #220: Setting default address using updateCustomer seems broken
Setting the `Customer` objects' `defaultAddress` field and calling `updateCustomer` does not change the `defaultAddress`. Is this field ignored for `updateCustomer` ?

### PR DESCRIPTION
**Pull request by krisorr**
# What this does
* makes Customer defaultAddress readOnly by removing the setter
* adds the "default" field to the Address POJO
* adds tests to make sure default Address is set properly on use of the Address Update endpoint

closes #220 

@sav007 , @davidmuzi , @bgulanowski please review

### CODE REVIEW

File: MobileBuy/buy/src/main/java/com/shopify/buy/model/Address.java [hunk 1]
```diff
@@ -62,12 +62,29 @@
 
     private String zip;
 
+    @SerializedName("default")
+    private Boolean defaultAddress;
```
Comment (sav007) [inline MobileBuy/buy/src/main/java/com/shopify/buy/model/Address.java]: Boolean not boolean? But we are not safe of NPE in isDefaultAddress()

File: MobileBuy/buy/src/main/java/com/shopify/buy/model/Address.java [hunk 2]
```diff
@@ -62,12 +62,29 @@
...
+
     @Override
     public Long getId() {
         return super.getId();
     }
 
     /**
+     * @param defaultAddress mark this as the default address for the associated {@link Customer}.
+     */
+    public void setDefaultAddress(Boolean defaultAddress) {
```
Comment (krisorr) [inline MobileBuy/buy/src/main/java/com/shopify/buy/model/Address.java]: @sav007 maybe this should be setAsDefaultAddress() ?

File: MobileBuy/buy/src/main/java/com/shopify/buy/model/Address.java (hunk 1 above)
Comment (krisorr) [inline MobileBuy/buy/src/main/java/com/shopify/buy/model/Address.java]: hmm, this is how we handle it in some other classes as well.  We don't want to use the primitive because we don't want to serialize/deserialize if the JSON does not have it set.
But in practice this value is always set on the JSON from the server so we haven't seen any issues.
Is will put a ticket in the backlog, we should be null checking in all the places we get the Boolean and convert to boolean just in case.

File: MobileBuy/buy/src/main/java/com/shopify/buy/model/Address.java (hunk 2 above)
Comment (sav007) [inline MobileBuy/buy/src/main/java/com/shopify/buy/model/Address.java]: I would like setDefault()

File: MobileBuy/buy/src/main/java/com/shopify/buy/model/Address.java (hunk 1 above)
Comment (krisorr) [inline MobileBuy/buy/src/main/java/com/shopify/buy/model/Address.java]: I switched it to Boolean for the property, and boolean for the getter and setter with a default value if Boolean property = null.

**Comment by sav007** [comment]
LGTM
